dist: trusty
sudo: requiered
language: php
php:
  - 7.1
servicies:
  - postgresql
install:
  - composer install
before_script:
  - cp .env.example .env
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - vendor/bin/phpunit
