dist: trusty
sudo: requiered
language: php
php:
  - 7.1.3
  - 7.2.9
  - nightly
servicies:
  - postgresql
install:
  - composer install
before_script:
  - cp .env.travis .env
  - psql -c 'create database travis;' -U postgres
  - php artisan migrate
script:
  - ./vendor/bin/phpunit
